
version: '3.8'

services:
  mongo:
    container_name: moviedb-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    container_name: moviedb-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
  movie-db-java:
    container_name: moviedb-java
    image: moviedb-java:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
